"""
AstroFS - Advanced File System Navigator
Python bindings for the Rust-based file system navigation tool.

This module provides comprehensive file system navigation, search,
bookmarking, theming, plugin support, and media playback capabilities.
"""

from typing import List, Dict, Optional
from enum import Enum

__version__: str

class FileEntry:
    """Represents a file system entry"""
    path: str
    name: str
    is_dir: bool
    size: int
    is_hidden: bool

class Workspace:
    """Represents a file system workspace state"""
    current_dir: str
    selected_index: int
    show_hidden: bool
    entries: List[FileEntry]

class Bookmark:
    """Represents a bookmarked directory"""
    path: str
    name: str
    icon: str

class BookmarkManager:
    """Manages bookmarks"""
    bookmarks: Dict[str, Bookmark]

class SearchEngine:
    """Provides search functionality"""
    pass

class ThemeManager:
    """Manages themes"""
    current_theme: str
    available_themes: List[str]

class Plugin:
    """Represents a loaded plugin"""
    id: str
    name: str
    description: str
    enabled: bool

class PluginManager:
    """Manages plugins"""
    plugins: List[Plugin]

class MediaPlayer:
    """Represents media player state"""
    state: str
    position: float
    volume: float
    speed: float
    repeat_mode: str
    current_index: int
    playlist: List[str]

class MediaPreview:
    """Provides media preview functionality"""
    pass

class PyAstroFS:
    """Main AstroFS interface for Python"""
    
    # Navigation
    def current_dir(self) -> str: ...
    def navigate(self, path: str) -> None: ...
    def move_up(self) -> None: ...
    def move_down(self) -> None: ...
    def go_to_path(self, path: str) -> None: ...
    def refresh(self) -> None: ...
    
    # File operations
    def list_files(self, show_hidden: Optional[bool] = None) -> List[FileEntry]: ...
    def get_selected_entry(self) -> Optional[FileEntry]: ...
    def create_file(self, name: str) -> None: ...
    def create_directory(self, name: str) -> None: ...
    def delete_selected(self) -> None: ...
    def delete_file(self, path: str) -> None: ...
    def rename_selected(self, new_name: str) -> None: ...
    def duplicate_selected(self) -> None: ...
    def toggle_hidden(self) -> None: ...
    
    # Search
    def search(self, pattern: str) -> None: ...
    def search_results(self) -> List[FileEntry]: ...
    def navigate_to_search_result(self, index: int) -> None: ...
    def clear_search(self) -> None: ...
    
    # Bookmarks
    def add_bookmark(self, name: str) -> None: ...
    def remove_bookmark(self, name: str) -> None: ...
    def goto_bookmark(self, name: str) -> None: ...
    def get_bookmark_manager(self) -> BookmarkManager: ...
    
    # Themes
    def list_themes(self) -> List[str]: ...
    def switch_theme(self, theme: str) -> None: ...
    def get_theme_manager(self) -> ThemeManager: ...
    
    # Plugins
    def load_plugins(self) -> None: ...
    def enable_plugin(self, plugin_id: str) -> None: ...
    def disable_plugin(self, plugin_id: str) -> None: ...
    def get_plugin_manager(self) -> PluginManager: ...
    
    # Media
    def play_media(self, path: str) -> None: ...
    def pause_media(self) -> None: ...
    def toggle_media_playback(self) -> None: ...
    def media_seek(self, seconds: float) -> None: ...
    def media_adjust_volume(self, delta: float) -> None: ...
    def media_adjust_speed(self, delta: float) -> None: ...
    def get_media_player(self) -> MediaPlayer: ...
    def get_media_status(self) -> str: ...
    
    # State
    def get_current_workspace(self) -> Workspace: ...
    def save_settings(self) -> None: ...
    def load_user_preferences(self) -> None: ...
    def export_settings(self, path: str) -> None: ...
    def import_settings(self, path: str) -> None: ...
